### ISSUE TITLE
Python  exception on subscription to watchlist

### ISSUE THREAD

**Issue by guindous** [mancuniancol/script.subscription.quasar.imdb#2]
Hi! I'm using this plugin to suscribe to my playlist at Imdb (ur0528666), but the script fails on subscription:

```
12:45:06 T:2812623680   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'simplejson.scanner.JSONDecodeError'>
                                            Error Contents: Expecting value: line 1 column 1 (char 0)
                                            Traceback (most recent call last):
                                              File "/home/guindus/.kodi/addons/script.subscription.quasar.imdb/service.py", line 104, in <module>
                                                update_service()
                                              File "/home/guindus/.kodi/addons/script.subscription.quasar.imdb/service.py", line 58, in update_service
                                                silence=True)
                                              File "/home/guindus/.kodi/addons/script.module.mctools/lib/tools2.py", line 1406, in subscription
                                                tvShow = TvShow(info['cleanTitle'])  # search the name without year
                                              File "/home/guindus/.kodi/addons/script.module.mctools/lib/tools2.py", line 870, in __init__
                                                data = response.json()
                                              File "/home/guindus/.kodi/addons/script.module.requests/lib/requests/models.py", line 808, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/home/guindus/.kodi/addons/plugin.video.quasar/resources/site-packages/simplejson/__init__.py", line 505, in loads
                                                return _default_decoder.decode(s)
                                              File "/home/guindus/.kodi/addons/plugin.video.quasar/resources/site-packages/simplejson/decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "/home/guindus/.kodi/addons/plugin.video.quasar/resources/site-packages/simplejson/decoder.py", line 400, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                              File "/home/guindus/.kodi/addons/plugin.video.quasar/resources/site-packages/simplejson/scanner.py", line 127, in scan_once
                                                return _scan_once(string, idx)
                                              File "/home/guindus/.kodi/addons/plugin.video.quasar/resources/site-packages/simplejson/scanner.py", line 87, in _scan_once
                                                raise JSONDecodeError(errmsg, string, idx)
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                            -->End of Python script error report<--
```

More info about the install:
Kodi 16 (jarvis). Linux version.

**Comment by mancuniancol** [comment]
I cannot reproduce the problem.  Could you confirm if you are using mctools version 1.3.6?
https://github.com/mancuniancol/script.module.mctools/archive/v1.3.6.zip

**Comment by mancuniancol** [comment]
Ok. I will close this issue, because I don't have any feedback

**Comment by guindous** [comment]
I was using 1.3.5 version of mctools. So I downloaded v1.3.6 (using the link you gave me) and the exception continues, same one. If you like I could provide you plugin conf, package installation version or help you tracing the problem. 

Sorry for the delayed answer.

**Comment by mancuniancol** [comment]
Yes please, and your log in debug mode

**Comment by guindous** [comment]
Mancuniacol i left the log here: [http://xbmclogs.com/phmwmgiyp](http://xbmclogs.com/phmwmgiyp)

Today I got some extra time for a simply debug of the problem. I think this is not a bug of you code is a quasar problem. First installed last quasar version. Then I follow the code and discover one of the Tv shows that has problems was "Flight of the Conchords" (https://www.themoviedb.org/tv/2742). So I navigate using quasar interface to this Tv Show And tried to go into season 0 (you could check it at the bottom of the log) and I result an Http Error. Just my 2 cents.

Again, sorry for the delay (again)
